# Generated by Django 4.1.3 on 2022-11-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.CharField(blank=True, db_column='1', max_length=255, null=True)),
                ('number_2', models.CharField(blank=True, db_column='2', max_length=255, null=True)),
                ('number_3', models.CharField(blank=True, db_column='3', max_length=255, null=True)),
                ('number_4', models.CharField(blank=True, db_column='4', max_length=255, null=True)),
                ('number_5', models.CharField(blank=True, db_column='5', max_length=255, null=True)),
                ('number_6', models.CharField(blank=True, db_column='6', max_length=255, null=True)),
                ('number_7', models.CharField(blank=True, db_column='7', max_length=255, null=True)),
            ],
            options={
                'db_table': 'timetable_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafedra', models.CharField(max_length=255)),
                ('kurs', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'timetable_week',
                'managed': False,
            },
        ),
    ]
